### ISSUE TITLE
Chapte 12: Models - Quantization

### ISSUE THREAD

**Issue by rendezvoush** [HandsOnLLM/Hands-On-Large-Language-Models#10]
On Google Colab

Even after the installation of the following

!pip install "bitsandbytes==0.43.1"
!pip install accelerate
#!pip install -U bitsandbytes

running "Models - Quantization", still can't go on. We got the following:

ImportError                               Traceback (most recent call last)
[<ipython-input-11-7d8e868d182e>](https://localhost:8080/#) in <cell line: 15>()
     13 
     14 # Load the model to train on the GPU
---> 15 model = AutoModelForCausalLM.from_pretrained(
     16     model_name,
     17     device_map="auto",

2 frames
[/usr/local/lib/python3.10/dist-packages/transformers/quantizers/quantizer_bnb_4bit.py](https://localhost:8080/#) in validate_environment(self, *args, **kwargs)
     64             raise ImportError("Using `bitsandbytes` 4-bit quantization requires Accelerate: `pip install accelerate`")
     65         if not is_bitsandbytes_available():
---> 66             raise ImportError(
     67                 "Using `bitsandbytes` 4-bit quantization requires the latest version of bitsandbytes: `pip install -U bitsandbytes`"
     68             )

ImportError: Using `bitsandbytes` 4-bit quantization requires the latest version of bitsandbytes: `pip install -U bitsandbytes`

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

Still can't find way to work it through, please help

**Comment by MaartenGr** [comment]
Thank you for sharing this issue! It seems that the pip installations were missing for the Google Colab notebooks. I'll make sure to add them either today or tomorrow. For now, the following should work:

```bash
%%capture
!pip install -q accelerate peft bitsandbytes transformers trl sentencepiece
```

What happened is that I removed the pip installations from the notebooks in the repo as those are meant for local usage. However, we are directly opening those notebooks in Google Colab. As such, I will add a section that allows you to get the right packages in each Colab notebook.

**Comment by rendezvoush** [comment]
Thanks!, It works now by uploading the requirements.txt and  install it with "!pip install -r requirements.txt"

**Comment by MaartenGr** [comment]
Awesome, glad to hear that it worked! I added additional instructions for installing the related packages when you are using Google Colab, so it should be more straightforward now.
