### ISSUE TITLE
Notebook 2 Not Found

### ISSUE THREAD

**Issue by f-amerehi** [HandsOnLLM/Hands-On-Large-Language-Models#12]
Hi, I hope you're doing well!
It seems there's an issue with Notebook 2. When trying to open it, it shows a 'Notebook not found' error.

Thank you very much.

![image](https://github.com/user-attachments/assets/5e29fcc0-28a1-410a-9568-8637355ec5fd)

**Comment by MaartenGr** [comment]
There seemed to be an additional "\" somewhere which messed up the link. Can you try it again? It works for me now.
