### ISSUE TITLE
Chapter 12 - Question about "Model Quantization" code

### ISSUE THREAD

**Issue by arunvasisht** [HandsOnLLM/Hands-On-Large-Language-Models#18]
I have a question related to below line of code in the notebook,

`model_name = "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"`

Question - Could you let me know, why this model is used for quantization and tokenization instead of using the one which was used for `template_tokenizer` i.e. "TinyLlama/TinyLlama-1.1BChat-v1.0". 

Context:
The intermediate-step model also does not have a chat template associated with it and I was getting following value error when attempting to train the SFTTrainer(). 

`ValueError: Cannot use chat template functions because tokenizer.chat_template is not set and no template argument was passed! For information about writing templates and setting the tokenizer.chat_template attribute, please see the documentation at https://huggingface.co/docs/transformers/main/en/chat_templating`

To fix my error, I used the "TinyLlama/TinyLlama-1.1BChat-v1.0" model for quantization and tokenization and the code ran successfully.

Could you therefore help clarify this choice of model in the code.

Thanks.

**Comment by arunvasisht** [comment]
Thanks @MaartenGr for the clarification. You are right in your assumption; I was asking about the line of code in the **Instruction Tuning with QLoRA** section of the book. 

Now as I read your response stating that we go _from base to chat model_, I understood it and the book made it clear as well. It makes sense that we want to fine tune a base model to be instruction tuned and it becomes a chat model. The fix that I inadvertently did to run my code was use a chat model to again become a chat model which is not what we wanted.

However, I am unable to run the code and I get the error as I mentioned in my question. I tried running locally as well and also on the Google Colab notebook. I was getting the same error. Could you suggest a solution or point me in the direction to solve it?

Thanks again!

**Comment by MaartenGr** [comment]
Ah, it seems that this is a result of an update to Transformers (see [this thread](https://discuss.huggingface.co/t/chat-template-is-not-set-throwing-error/104095/2)). For now, you have one of two options. 

You can downgrade your Transformers version to the exact requirements shown [here](https://github.com/HandsOnLLM/Hands-On-Large-Language-Models/blob/main/requirements.txt). These requirements are fixed and are used to reproduce the contents of the book as best as possible. 

Or... we can simply steal the chat template that we want to reproduce by doing this after loading our `tokenizer` :

```python
tokenizer.chat_template = template_tokenizer.chat_template
```

**Comment by arunvasisht** [comment]
Thanks @MaartenGr 

The solution you provided [here](https://github.com/HandsOnLLM/Hands-On-Large-Language-Models/issues/18#issuecomment-2507540451) works well. I did not have to downgrade my transformer version.

I used the same _chat_template_ as the _tokenizer_template_ and it worked like a charm.

Do you think, this extra line of code be updated in the notebook so that others may not face this issue again?

Thanks.

**Comment by MaartenGr** [comment]
@arunvasisht I want to stay as true to the original code in the book as much as possible. Otherwise, there might be confusion. That said, I think a solution would either be to fix the transformer version (as is done in `requirements.txt`) or indeed as you mentioned update that line of code. It should be made transparent though that this might actually be a temporary issue if I read the thread I linked previously well. 

What do you think?
