### ISSUE TITLE
Chapter 9 - Running Error

### ISSUE THREAD

**Issue by jyellow** [HandsOnLLM/Hands-On-Large-Language-Models#21]
I run Code on Colab, in this [cell code](https://colab.research.google.com/github/HandsOnLLM/Hands-On-Large-Language-Models/blob/main/chapter09/Chapter%209%20-%20Multimodal%20Large%20Language%20Models.ipynb#scrollTo=gFJ9-l8c8u3i),
```python
# Load an AI-generated image of a supercar
image = Image.open(urlopen(car_path)).convert("RGB")

# Convert an image into inputs and preprocess it
inputs = blip_processor(image, return_tensors="pt").to(device, torch.float16)
image
```

and get this error message
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-24-4e509c2e1006> in <cell line: 2>()
      1 # Generate image ids to be passed to the decoder (LLM)
----> 2 generated_ids = model.generate(**inputs, max_new_tokens=20)
      3 
      4 # Generate text from the image ids
      5 generated_text = blip_processor.batch_decode(generated_ids, skip_special_tokens=True)

/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py in decorate_context(*args, **kwargs)
    114     def decorate_context(*args, **kwargs):
    115         with ctx_factory():
--> 116             return func(*args, **kwargs)
    117 
    118     return decorate_context

/usr/local/lib/python3.10/dist-packages/transformers/models/blip_2/modeling_blip_2.py in generate(self, pixel_values, input_ids, attention_mask, interpolate_pos_encoding, **generate_kwargs)
   2314         if getattr(self.config, "image_token_index", None) is not None:
   2315             special_image_mask = (input_ids == self.config.image_token_index).unsqueeze(-1).expand_as(inputs_embeds)
-> 2316             inputs_embeds[special_image_mask] = language_model_inputs.flatten()
   2317         else:
   2318             logger.warning_once(

RuntimeError: shape mismatch: value tensor of shape [81920] cannot be broadcast to indexing result of shape [0]
```

If I modify the code to add the `text` parameter to the `blip_processor`, it works successfully. However, I don’t know why. Could you please explain? Thank you!
```python
image = Image.open(urlopen(car_path)).convert("RGB")

prompt = "Question: Write down what you see in this picture. Answer:"
inputs = blip_processor(image, text=prompt, return_tensors="pt").to(device, torch.float16)
```

**Comment by MaartenGr** [comment]
@jyellow Could you try it again with the versions as defined in `requirements.txt`? It seems that with the frequent updates on these packages it might be helpful to pin those versions.

**Comment by jyellow** [comment]
> @jyellow Could you try it again with the versions as defined in `requirements.txt`? It seems that with the frequent updates on these packages it might be helpful to pin those versions.

OK, I will try.

**Comment by MaartenGr** [comment]
Apologies for the late reply, I have been sick last week. Fortunately, I think I found a solution for your problem. 

Instead of this:

```python
blip_processor = AutoProcessor.from_pretrained("Salesforce/blip2-opt-2.7b")
```

could you try this:

```python
blip_processor = AutoProcessor.from_pretrained("Salesforce/blip2-opt-2.7b", revision="51572668da0eb669e01a189dc22abe6088589a24")
```

It seems that the model was updated to account for changes in Transformers (see the discussion [here](https://huggingface.co/Salesforce/blip2-opt-2.7b/discussions/39)), which makes version control more difficult since we now need to version control both the code as well as the model...

That said, I think (and hope) that this will solve it as it would need only a small change in the code.

**Comment by jyellow** [comment]
> Apologies for the late reply, I have been sick last week. Fortunately, I think I found a solution for your problem.
> 
> Instead of this:
> 
> ```python
> blip_processor = AutoProcessor.from_pretrained("Salesforce/blip2-opt-2.7b")
> ```
> 
> could you try this:
> 
> ```python
> blip_processor = AutoProcessor.from_pretrained("Salesforce/blip2-opt-2.7b", revision="51572668da0eb669e01a189dc22abe6088589a24")
> ```
> 
> It seems that the model was updated to account for changes in Transformers (see the discussion [here](https://huggingface.co/Salesforce/blip2-opt-2.7b/discussions/39)), which makes version control more difficult since we now need to version control both the code as well as the model...
> 
> That said, I think (and hope) that this will solve it as it would need only a small change in the code.

@MaartenGr thanks, this code is fine, and I'm so sorry that you have been sick, I hope you feel good now.
```python
from transformers import AutoProcessor, Blip2ForConditionalGeneration
import torch

# Load processor and main model
# blip_processor = AutoProcessor.from_pretrained("Salesforce/blip2-opt-2.7b")
blip_processor = AutoProcessor.from_pretrained(
    "Salesforce/blip2-opt-2.7b",
    revision="51572668da0eb669e01a189dc22abe6088589a24")

model = Blip2ForConditionalGeneration.from_pretrained(
    "Salesforce/blip2-opt-2.7b",
    torch_dtype=torch.float16,
    revision="51572668da0eb669e01a189dc22abe6088589a24"
)

# Send the model to GPU to speed up inference
device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
```

**Comment by MaartenGr** [comment]
@jyellow Thank you for your insights on this. I just pushed a fix 😄
