### ISSUE TITLE
Errata in Chapter 11 - Page 338

### ISSUE THREAD

**Issue by arunvasisht** [HandsOnLLM/Hands-On-Large-Language-Models#23]
I noticed a small error in the text 
`... which would be  20 * 32 = 680 samples. We will have to multiply this value by 2 for each positive and negative pair generated, 680 * 2 = 1,280 sentence pairs.`

**It should be 640 and not 680**

Thanks.

**Comment by MaartenGr** [comment]
Great, thanks for passing this along! I just added it to the official errata of the book. If we ever make a second version, these changes will definitely be included. Thanks again!
