### ISSUE TITLE
Chapter#8: Notebook, RAG, Load Quantized Model 

### ISSUE THREAD

**Issue by dcarpintero** [HandsOnLLM/Hands-On-Large-Language-Models#25]
Page 252, last paragraph of the book (printed version) reads: "_we'll start by downloading a **quantized** model_", but in the code snippet of the notebook it uses the model "**_Phi-3-mini-4k-instruct-fp16.gguf_**" as follows:

!wget https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf/resolve/main/Phi-3-mini-4k-instruct-fp16.gguf

llm = LlamaCpp(
    model_path="**Phi-3-mini-4k-instruct-fp16.gguf**",
    n_gpu_layers=-1,
    max_tokens=500,
    n_ctx=2048,
    seed=42,
    verbose=False
)

- **Phi-3-mini-4k-instruct-fp16.gguf** is according to the [model card](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf)  not a quantized model, but a full precission 16 bit version.

- The quantized version for this model is listed in the card as: **Phi-3-mini-4k-instruct-q4.gguf**, a 4-bit quantized version.

**Comment by MaartenGr** [comment]
Apologies for the late reply and thank you for sharing this! It seems that this was not properly updated when editing the book. I'll take a look at the PR 😄
