### ISSUE TITLE
Chapter#8: Notebook, RAG, Match BGE Model

### ISSUE THREAD

**Issue by dcarpintero** [HandsOnLLM/Hands-On-Large-Language-Models#26]
Page 253 of the printed version (printed version) refers to using the "**BAAI/bge-small-en-v1.5**" model, however in the code snippet it uses "**thenlper/gte-small**":

embedding_model = HuggingFaceEmbeddings(
    model_name='**thenlper/gte-small**'
)

**Comment by MaartenGr** [comment]
Yep, an artifact of older edits that shouldn't be there. Thank you for taking the time to share this and even create a PR!
