### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [HandsOnLLM/Hands-On-Large-Language-Models#4]
Hi @jalammar and @MaartenGr ,

congratulations to the fantastic book and big thanks for sharing these notebooks open source! I was just wondering under which conditions one could reuse the code and materials provided here, e.g. as part of training redources in other repisitories. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by negativenagesh** [comment]
### Hi @haesleinhuepf as per your issue https://github.com/HandsOnLLM/Hands-On-Large-Language-Models/issues/4 

I have added Apache License with - 'Copyright 2024 HandsOnLLM' with pull request - https://github.com/HandsOnLLM/Hands-On-Large-Language-Models/pull/9  please check out the files changed on https://github.com/HandsOnLLM/Hands-On-Large-Language-Models/pull/9  and resolve this issue.

### **Waiting for @MaartenGr to review and Merge this pull request #9 !!!!**

**Comment by MaartenGr** [comment]
Thank you for the suggestions! I will talk it over with Jay and the publisher to decide which license we are choosing. However, most likely it will be an MIT or Apache license for the code itself. We might have to update it a bit to mention specifically that it does not include any images or content otherwise derived directly from the book but I'll have to check.

**Comment by negativenagesh** [comment]
Thank you!!

**Comment by bbruceyuan** [comment]
> Thank you for the suggestions! I will talk it over with Jay and the publisher to decide which license we are choosing. However, most likely it will be an MIT or Apache license for the code itself. We might have to update it a bit to mention specifically that it does not include any images or content otherwise derived directly from the book but I'll have to check.

May I ask which license you have decided to use now? 
I hope I can made a series of LLM Chinese teaching Video according to your notebook. it will link to your github/website.

**Comment by MaartenGr** [comment]
@bbruceyuan You will be able to! I have to find time somewhere this week to add the license but I can already promise it will be permissive.

**Comment by MaartenGr** [comment]
@bbruceyuan @haesleinhuepf Pfew, finally found some time to do something that takes like 1 minute 😅 Either way, we added a permissive license, so feel free to use the code in your presentations/videos/etc. 

If there is anything unclear related to this or otherwise, feel free to reach out!
